import "./globals.css"
import type { Metadata } from "next"
import Toaster from "@/components/Toaster"
import Container from "@/components/Container"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='zh-Hant-TW'>
            <body>
                <Toaster />
                <Container>{children}</Container>
            </body>
        </html>
    )
}
